[project]
name = "one-sentence-summaries"
version = "0.1.0"
description = "A subset of book descriptions from https://openlibrary.org"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
